---
- include: do_reconfigure.yml
  serial: "30%"
  when: inventory_hostname in groups['neutron-server']
        or (enable_manila | bool and inventory_hostname in groups['manila-share'])
        or inventory_hostname in groups['compute']
        or inventory_hostname in groups['neutron-dhcp-agent']
        or inventory_hostname in groups['neutron-l3-agent']
        or inventory_hostname in groups['neutron-lbaas-agent']
        or inventory_hostname in groups['neutron-metadata-agent']
