FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
MAINTAINER {{ maintainer }}

ADD plugins-archive /
COPY extend_start.sh /usr/local/bin/kolla_neutron_extend_start
RUN chmod 755 /usr/local/bin/kolla_neutron_extend_start \
    && if [ "$(ls /plugins)" ]; then \
           pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt /plugins/*; \
       fi && pip --no-cache-dir install --upgrade -c requirements/upper-constraints.txt http://tarballs.openstack.org/neutron-lbaas/neutron_lbaas-8.0.0-py2.py3-none-any.whl

{{ include_footer }}

USER neutron
